"""Rebuilds lib/widgets/india_outline.dart from the DataMeet India composite boundary, which follows
the Government of India official map (github.com/datameet/maps, Country/india-composite.geojson).

    curl -o /tmp/india-composite.geojson https://raw.githubusercontent.com/datameet/maps/master/Country/india-composite.geojson
    python tools/build_india_outline.py
"""
import json, math, os

SRC = '/tmp/india-composite.geojson'
OUT = os.path.join(os.path.dirname(__file__), '..', 'lib', 'widgets', 'india_outline.dart')

def area(r):
    return abs(sum(r[i][0] * r[i + 1][1] - r[i + 1][0] * r[i][1] for i in range(len(r) - 1))) / 2

def dp(pts, eps):
    """Iterative Douglas-Peucker on an open polyline."""
    keep = [False] * len(pts); keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = pts[a]; bx, by = pts[b]
        dx, dy = bx - ax, by - ay
        L = math.hypot(dx, dy)
        best, bi = -1.0, -1
        for i in range(a + 1, b):
            px, py = pts[i]
            d = math.hypot(px - ax, py - ay) if L == 0 else abs(dy * px - dx * py + bx * ay - by * ax) / L
            if d > best: best, bi = d, i
        if bi >= 0 and best > eps:
            keep[bi] = True
            stack += [(a, bi), (bi, b)]
    return [p for p, k in zip(pts, keep) if k]

def simplify_ring(ring, eps):
    """Split a closed ring at the point farthest from its start, simplify both halves, rejoin."""
    pts = ring[:-1] if ring[0] == ring[-1] else ring
    far = max(range(len(pts)), key=lambda i: math.hypot(pts[i][0] - pts[0][0], pts[i][1] - pts[0][1]))
    first = dp(pts[: far + 1], eps)
    second = dp(pts[far:] + [pts[0]], eps)
    return first[:-1] + second[:-1]

polys = sorted((p[0] for p in json.load(open(SRC))['features'][0]['geometry']['coordinates']), key=area, reverse=True)
rings = [simplify_ring(polys[0], 0.05)]
rings += [simplify_ring(r, 0.02) for r in polys[1:] if area(r) > 0.03]
rings = [r for r in rings if len(r) >= 4]

lines = [
    '// GENERATED by tools/build_india_outline.py from the DataMeet India composite boundary',
    '// (github.com/datameet/maps, Country/india-composite.geojson), which follows the Government of',
    "// India official boundary. Simplified with Douglas-Peucker for drawing. Do not edit by hand.",
    '',
    '/// Longitude/latitude rings: the mainland first, then the larger islands.',
    'const List<List<List<double>>> indiaOutline = [',
]
for r in rings:
    lines.append('  [' + ', '.join(f'[{x:.3f}, {y:.3f}]' for x, y in r) + '],')
lines.append('];')
open(OUT, 'w').write('\n'.join(lines) + '\n')
print('rings:', len(rings), 'points per ring:', [len(r) for r in rings])
print('island centres:', [(round(sum(p[0] for p in r) / len(r), 1), round(sum(p[1] for p in r) / len(r), 1)) for r in rings[1:]])
